name: Test jfrog cli
on:
  workflow_dispatch:

jobs:
  cli:
    runs-on: ubuntu-latest

    steps:
      -
        uses: 'jfrog/setup-jfrog-cli@v4'
        env:
          JF_URL: 'foobar'
          JF_ACCESS_TOKEN: '123'
        with:
          download-repository: 'jfrog-cli-remote'
